/**
 * NWEN 302 Lab 1
 * ARP Main File
 * Do not edit this file
 *
 * Please report bugs to the author.
 *
 * Copyright (C) 2021 by Alvin Valera <alvin.valera@vuw.ac.nz>
 * All rights reserved.
 */

#include <stdio.h>
#include <string.h>
#include <stdlib.h>
#include <unistd.h>
#include <errno.h>

#include <arpa/inet.h>
#include <net/if.h>
#include <net/if_arp.h>
#include <netinet/in.h>
#include <netinet/ip.h>
#include <netinet/ether.h>
#include <linux/if_packet.h>
#include <sys/ioctl.h>
#include <sys/socket.h>
       
#include "arp_functions.h"
#include "my_arp.h"


#define BUFLEN  65536

/* IPv4 address of the default device eth0 */
extern uint32_t my_ip_address;

/* MAC address of the default device eth0 */
extern unsigned char my_mac_address[6];

/* The interface index of eth0 */
extern int iface_index;

/**
 * Handle an incoming or outgoing packet
 */
void handle_packet(char *buffer, int len)
{
    struct ethhdr *eth = (struct ethhdr *)buffer;
        
    /* Check if ARP packet */
    if(ntohs(eth->h_proto) == ETH_P_ARP) {
        struct arphdr *arph = (struct arphdr*)(buffer + sizeof(struct ethhdr));
        uint32_t target_ip, source_ip;
        memcpy(&target_ip, buffer + sizeof(struct ethhdr) + sizeof(struct arphdr) + 2*arph->ar_hln + arph->ar_pln, arph->ar_pln);
        memcpy(&source_ip, buffer + sizeof(struct ethhdr) + sizeof(struct arphdr) + arph->ar_hln, arph->ar_pln);
        unsigned char *target_mac = buffer + sizeof(struct ethhdr) + sizeof(struct arphdr) + arph->ar_hln + arph->ar_pln;        
        unsigned char *source_mac = buffer + sizeof(struct ethhdr) + sizeof(struct arphdr); 
        if(ntohs(arph->ar_op) == ARPOP_REQUEST) {
            /* We only want to handle ARP requests coming from other nodes */
            if(memcmp(eth->h_source, my_mac_address, 6) != 0) {
                printf("Received ARP request packet, telling ARP.\n");
                my_arp_handle_request(ntohl(target_ip), source_mac);
            }
        } else if(ntohs(arph->ar_op) == ARPOP_REPLY) {
            /* We only want to handle ARP replies for this node */
            if(memcmp(eth->h_dest, my_mac_address, 6) == 0) {  
                printf("Received ARP reply packet, telling my_arp.\n");
                my_arp_handle_reply(source_ip, source_mac);
            }
        } else {
            /* XXX: Do nothing for now */
        }
        return;
    }
    
    /* Otherwise, see what we can do with it */
    struct iphdr *iph = (struct iphdr*)(buffer + sizeof(struct ethhdr));
    char anyaddr[6] = {0};
    char bcast[6] = {0xff, 0xff, 0xff, 0xff, 0xff, 0xff};
    if(memcmp(eth->h_source, eth->h_dest, 6) == 0) {
        if(memcmp(anyaddr, eth->h_dest, 6) != 0) {
            /* Frame has no valid dest address, tell ARP */
            printf("Destination address not valid, telling my_arp.\n");
            my_arp_resolve ((uint32_t) ntohl(iph->daddr));
        } else {
            /* XXX: Do nothing for now */
        }
    } else {
        if(memcmp(bcast, eth->h_dest, 6) != 0) {
            /* Tell someone about this packet so they can refresh some of their data structures :) */
            my_arp_frame_transmitted((uint32_t) ntohl(iph->daddr), eth->h_dest);   
        } else {
            /* XXX: Do nothing for now */
        }
    }
}

/**
 * Display Ethernet header
 * Only used for debugging purpose
 */
void print_eth_header(char* buffer)
{
	struct ethhdr *eth = (struct ethhdr *)buffer;
	
	printf("Ethernet Header\n");
	printf("  |-Destination Address : %.2x:%.2x:%.2x:%.2x:%.2x:%.2x \n", eth->h_dest[0] , eth->h_dest[1] , eth->h_dest[2] , eth->h_dest[3] , eth->h_dest[4] , eth->h_dest[5] );
	printf("  |-Source Address      : %.2x:%.2x:%.2x:%.2x:%.2x:%.2x \n", eth->h_source[0] , eth->h_source[1] , eth->h_source[2] , eth->h_source[3] , eth->h_source[4] , eth->h_source[5] );
	printf("  |-Protocol            : %.4X \n", (unsigned short)ntohs(eth->h_proto));
}

/**
 * Get interface IP and MAC address and save them
 */
void get_iface_addrs()
{
    char iface[] = "eth0"; /* We assume that the node has only one interface called eth0! */
    struct ifreq ifr;
    
	int fd = socket(AF_INET, SOCK_DGRAM, 0);
	ifr.ifr_addr.sa_family = AF_INET;
	strncpy(ifr.ifr_name , iface , strlen(iface)+1);
	ioctl(fd, SIOCGIFADDR, &ifr);
    struct sockaddr_in* ipaddr = (struct sockaddr_in*)&ifr.ifr_addr;
    memcpy(&my_ip_address, &ipaddr->sin_addr, 4);
    my_ip_address = ntohl(my_ip_address);
    
    ioctl(fd, SIOCGIFHWADDR, &ifr);
    memcpy(my_mac_address, &ifr.ifr_addr.sa_data, 6);
    
    ioctl(fd, SIOCGIFINDEX, &ifr);
    iface_index = ifr.ifr_ifindex;

    close(fd);
}


/**
 * The main function.
 * For now, we don't accept command line arguments.
 */
int main(int argc, char *argv[])
{
    int ret = 0;
    extern int socket_fd;
    char buffer[BUFLEN];
    struct sockaddr_ll saddr;

    /* Check if running as root */
    if(geteuid() != 0) {
        printf("Error: this program must be run as root or using sudo.\n");
        return -1;
    }
    
    /* Disable arp on interface */
    system("ip link set dev eth0 arp off");

    /* Get IP and MAC address of eth0 */
    get_iface_addrs();
    struct in_addr in = { htonl(my_ip_address) };
    char *ip_str = inet_ntoa(in);
    printf("eth0 IP address : %s\n", ip_str);
    printf("eth0 MAC address: %.2x:%.2x:%.2x:%.2x:%.2x:%.2x\n", my_mac_address[0], my_mac_address[1], 
           my_mac_address[2], my_mac_address[3], my_mac_address[4], my_mac_address[5]);
    
    
    /* Create raw socket to snoop for packets */
    if((socket_fd = socket(AF_PACKET, SOCK_RAW, htons(ETH_P_ALL))) == -1) {
        printf("Error: %s (%d)\n", strerror(errno), errno);
        return errno;
    }
    
    /* Call my_arp_init() */
    my_arp_init();
    
    /* Main loop to receive data from tap interface */
    struct sockaddr addr;
    int addrlen = sizeof(addr);
    while (1) {
        int len = recvfrom(socket_fd, buffer, BUFLEN, 0, &addr, (socklen_t*)&addrlen);
        if (len < 0) {
            printf("Error: Failed to receive packets.\n");
            break;
        } else {
            //printf("Received packet of length %d\n", len);
            handle_packet(buffer, len);
            //print_eth_header(buffer);
        }
    }
    
    /* Close socket */
    close(socket_fd);

    return 0;
}
