/**
 * NWEN302 Lab 1
 * List of functions that you can use in your implementation.
 * Do not edit this file. 
 *
 * Please report bugs to the author.
 *
 * Copyright (C) 2021 by Alvin Valera <alvin.valera@vuw.ac.nz>
 * All rights reserved.
 */

#include <stdio.h>
#include <stdlib.h>
#include <string.h>

#include <sys/socket.h>
#include <netinet/in.h>
#include <arpa/inet.h>
#include <net/if.h>
#include <net/if_arp.h>
#include <net/ethernet.h>
#include <linux/if_packet.h>              

#include "arp_functions.h"


/* This node's IP address */
uint32_t my_ip_address;

/* This node's MAC address */
unsigned char my_mac_address[6];

/* The interface index */
int iface_index;

/* Socket file descriptor */
int socket_fd;

/**
 * Insert an entry in the ARP cache.
 * 
 * @param ip_address IPv4 address
 * @param mac_address MAC address of the interface with @ip_address.
 * This should be a 48-bit MAC address.
 */ 
void arp_insert_cache(uint32_t ip_address, const unsigned char *mac_address)
{
    char cmd[100];
    struct in_addr in = { ip_address };
    char *ip_str = inet_ntoa(in);
    char mac_str[18] = {0};
    snprintf(mac_str, 18, "%.2x:%.2x:%.2x:%.2x:%.2x:%.2x", mac_address[0], mac_address[1], mac_address[2], mac_address[3], mac_address[4], mac_address[5]);
    snprintf(cmd, 100, "arp -s %s %s", ip_str, mac_str);
    printf("Invoking %s\n", cmd);
    system(cmd);
}


/**
 * Delete an entry in the ARP cache
 * 
 * @param ip_address IPv4 address
 */ 
void arp_delete_cache(uint32_t ip_address)
{
    char cmd[100];
    struct in_addr in = { ip_address };
    char *ip_str = inet_ntoa(in);
    snprintf(cmd, 100, "arp -d %s", ip_str);
    printf("Invoking %s\n", cmd);
    system(cmd);
}


/**
 * Send an ARP query. When you use/call this function, make sure
 * you are providing the correct input parameters
 * 
 * @param ip_address IPv4 address to be resolved
 * @param dest_mac_address Destination MAC address to send to. This 
 * should be a 48-bit MAC address.
 *
 * @return 0 if successful, < 0 otherwise.
 */ 
int arp_send_query(uint32_t ip_address, const unsigned char *dest_mac_address)
{
    char buffer[1000] = {};

    /* Compose Ethernet header */    
    struct ethhdr *eth = (struct ethhdr *)buffer;
    memcpy(eth->h_source, my_mac_address, 6);
    memcpy(eth->h_dest, dest_mac_address, 6); 
    eth->h_proto = htons(ETH_P_ARP);
    
    /* Compose ARP header */
    struct arphdr *arph = (struct arphdr*)(buffer + sizeof(struct ethhdr));
    arph->ar_hrd = htons(ARPHRD_ETHER); 
    arph->ar_pro = htons(ETH_P_IP); 
    arph->ar_hln = 6;
    arph->ar_pln = 4;
    arph->ar_op = htons(ARPOP_REQUEST);
    
    /* Fill in rest of the contents */
    struct arpdata *arpd = (struct arpdata*)(buffer + sizeof(struct ethhdr) + sizeof(struct arphdr));
    memcpy(arpd->ar_sha, my_mac_address, 6);
    arpd->ar_sip = htonl(my_ip_address);
    arpd->ar_tip = htonl(ip_address);

    /* Send */
    struct sockaddr_ll addr;
    int addrlen = sizeof(addr); 
    int txlen =  sizeof(struct ethhdr) + sizeof(struct arphdr) + sizeof(struct arpdata); 
	addr.sll_ifindex = iface_index;
	addr.sll_halen = ETH_ALEN;
	memcpy(addr.sll_addr, dest_mac_address, 6); 
	return sendto(socket_fd, buffer, txlen, 0, (struct sockaddr*)&addr, sizeof(struct sockaddr_ll));
}


/**
 * Send an ARP reply. When you use/call this function, make sure
 * the Ethernet frame is formed correctly
 * 
 * @param eth_frame Raw Ethernet frame to be transmitted.
 * @param len Length of the entire Ethernet frame.
 *
 * @return 0 if successful, < 0 otherwise. 
 */ 
int arp_send_reply(char *eth_frame, int len) 
{
    struct ethhdr *eth = (struct ethhdr *)eth_frame;
    struct sockaddr_ll addr;
    int addrlen = sizeof(addr); 
    int txlen =  len; 
	addr.sll_ifindex = iface_index;
	addr.sll_halen = ETH_ALEN;
	memcpy(addr.sll_addr, eth->h_dest, 6); 
	return sendto(socket_fd, eth_frame, txlen, 0, (struct sockaddr*)&addr, sizeof(struct sockaddr_ll));
}

/**
 * Get this nodes IP address
 * 
 * @return IPv4 address of this node.
 */ 
uint32_t arp_get_my_ipaddr()
{
    return my_ip_address;
}

/** 
 * Get the 48-bit MAC address of this node.
 * 
 * @param buffer Buffer to store the MAC address (should be at least 6 bytes!)
 */
void arp_get_my_macaddr(unsigned char *buffer)
{
    memcpy(buffer, my_mac_address, 6);
}
