/**
 * NWEN302 Lab 1
 * List of functions that you can use in your implementation.
 * Do not edit this file. 
 *
 * Please report bugs to the author.
 *
 * Copyright (C) 2021 by Alvin Valera <alvin.valera@vuw.ac.nz>
 * All rights reserved.
 */


#ifndef __LSWITCH_FUNCTIONS_H__
#define __LSWITCH_FUNCTIONS_H__ 

#include <stdint.h>
#include <sys/socket.h>
#include <netinet/in.h>
#include <arpa/inet.h>

#include <linux/if_ether.h>


/**
 * Insert an entry in the switch table. Make sure that the entry to be inserted
 * is not a duplicate, otherwise, there might be undefined behaviour.
 * 
 * @param mac_address MAC address. This should be a 48-bit MAC address.
 * @param device Name of interface where the node with @mac_address is attached.
 */ 
void lswitch_insert_table(const unsigned char *mac_address, const char *device);

/**
 * Delete an entry in the switch table. Make sure that the entry to be deleted
 * exists, otherwise, there might be undefined behaviour.
 * 
 * @param mac_address MAC address. This should be a 48-bit MAC address.
 * @param device Name of interface where the node with @mac_address is attached.
 */ 
void lswitch_delete_table(const unsigned char *mac_address, const char *device);

#endif /* __LSWITCH_FUNCTIONS_H__ */
