/**
 * NWEN302 Lab 1
 * List of functions that you can use in your implementation.
 * Do not edit this file. 
 *
 * Please report bugs to the author.
 *
 * Copyright (C) 2021 by Alvin Valera <alvin.valera@vuw.ac.nz>
 * All rights reserved.
 */

#include <stdio.h>
#include <stdlib.h>
#include <string.h>

#include <sys/socket.h>
#include <netinet/in.h>
#include <arpa/inet.h>
#include <net/if.h>
#include <net/if_arp.h>
#include <net/ethernet.h>
#include <linux/if_packet.h>              

#include "lswitch_functions.h"


/**
 * Insert an entry in the switch table.
 * 
 * @param mac_address MAC address. This should be a 48-bit MAC address.
 * @param device Name of interface where the node with @mac_address is attached.
 */ 
void lswitch_insert_table(const unsigned char *mac_address, const char *device)
{
    char cmd[100];
    char mac_str[18] = {0};
    snprintf(mac_str, 18, "%.2x:%.2x:%.2x:%.2x:%.2x:%.2x", mac_address[0], mac_address[1], mac_address[2], mac_address[3], mac_address[4], mac_address[5]);
    snprintf(cmd, 100, "bridge fdb add %s dev %s master static via br0", mac_str, device);
    printf("Invoking %s\n", cmd);
    system(cmd);
}

/**
 * Delete an entry in the switch table.
 * 
 * @param mac_address MAC address. This should be a 48-bit MAC address.
 * @param device Name of interface where the node with @mac_address is attached.
 */ 
void lswitch_delete_table(const unsigned char *mac_address, const char *device)
{
    char cmd[100];
    char mac_str[18] = {0};
    snprintf(mac_str, 18, "%.2x:%.2x:%.2x:%.2x:%.2x:%.2x", mac_address[0], mac_address[1], mac_address[2], mac_address[3], mac_address[4], mac_address[5]);
    snprintf(cmd, 100, "bridge fdb del %s dev %s master static via br0", mac_str, device);
    printf("Invoking %s\n", cmd);
    system(cmd);

}
